# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtWidgets, QtGui, QtCore

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1280, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/pitch.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1281, 691))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 80))
        self.tabWidget.setIconSize(QtCore.QSize(25, 25))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 190, 371, 151))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.progressBarThrottle = QtWidgets.QProgressBar(self.groupBox)
        self.progressBarThrottle.setGeometry(QtCore.QRect(230, 30, 121, 23))
        self.progressBarThrottle.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBarThrottle.setProperty("value", 76)
        self.progressBarThrottle.setObjectName(_fromUtf8("progressBarThrottle"))
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(50, 30, 81, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.progressBarYaw = QtWidgets.QProgressBar(self.groupBox)
        self.progressBarYaw.setGeometry(QtCore.QRect(230, 60, 121, 23))
        self.progressBarYaw.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBarYaw.setMinimum(-100)
        self.progressBarYaw.setProperty("value", 0)
        self.progressBarYaw.setObjectName(_fromUtf8("progressBarYaw"))
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(50, 60, 81, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.progressBarAUX = QtWidgets.QProgressBar(self.groupBox)
        self.progressBarAUX.setGeometry(QtCore.QRect(230, 90, 121, 23))
        self.progressBarAUX.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBarAUX.setProperty("value", 0)
        self.progressBarAUX.setObjectName(_fromUtf8("progressBarAUX"))
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(50, 90, 81, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(50, 120, 81, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.progressBarAU = QtWidgets.QProgressBar(self.groupBox)
        self.progressBarAU.setGeometry(QtCore.QRect(230, 120, 121, 23))
        self.progressBarAU.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBarAU.setProperty("value", 100)
        self.progressBarAU.setObjectName(_fromUtf8("progressBarAU"))
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 20, 371, 151))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 40, 181, 21))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 70, 181, 21))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 100, 181, 21))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(230, 40, 121, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet(_fromUtf8("color:rgb(255, 0, 0)"))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(230, 70, 121, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet(_fromUtf8("color:rgb(255, 0, 0)"))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(230, 100, 121, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet(_fromUtf8("color:#FF0000"))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(400, 20, 371, 151))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(50, 30, 81, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(220, 30, 121, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet(_fromUtf8("color:#FF0000"))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(40, 60, 111, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(40, 90, 111, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_23 = QtWidgets.QLabel(self.groupBox_3)
        self.label_23.setGeometry(QtCore.QRect(40, 120, 111, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtWidgets.QLabel(self.groupBox_3)
        self.label_24.setGeometry(QtCore.QRect(220, 60, 121, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet(_fromUtf8("color:rgb(0, 170, 0)"))
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_25 = QtWidgets.QLabel(self.groupBox_3)
        self.label_25.setGeometry(QtCore.QRect(220, 90, 121, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet(_fromUtf8("color:rgb(0, 170, 0)"))
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_26 = QtWidgets.QLabel(self.groupBox_3)
        self.label_26.setGeometry(QtCore.QRect(220, 120, 121, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet(_fromUtf8("color:#FF0000"))
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(770, 20, 481, 611))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setGeometry(QtCore.QRect(10, 30, 81, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.graphicsView = QOSM(self.groupBox_4)
        self.graphicsView.setGeometry(QtCore.QRect(10, 190, 471, 261))
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setGeometry(QtCore.QRect(10, 170, 101, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtWidgets.QLabel(self.groupBox_4)
        self.label_17.setGeometry(QtCore.QRect(30, 480, 101, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtWidgets.QLabel(self.groupBox_4)
        self.label_18.setGeometry(QtCore.QRect(240, 480, 101, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_19 = QtWidgets.QLabel(self.groupBox_4)
        self.label_19.setGeometry(QtCore.QRect(20, 540, 151, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtWidgets.QLabel(self.groupBox_4)
        self.label_20.setGeometry(QtCore.QRect(240, 560, 101, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtWidgets.QLabel(self.groupBox_4)
        self.label_21.setGeometry(QtCore.QRect(30, 560, 101, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtWidgets.QLabel(self.groupBox_4)
        self.label_22.setGeometry(QtCore.QRect(30, 500, 101, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_27 = QtWidgets.QLabel(self.groupBox_4)
        self.label_27.setGeometry(QtCore.QRect(120, 480, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_28 = QtWidgets.QLabel(self.groupBox_4)
        self.label_28.setGeometry(QtCore.QRect(340, 480, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_29 = QtWidgets.QLabel(self.groupBox_4)
        self.label_29.setGeometry(QtCore.QRect(120, 560, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_30 = QtWidgets.QLabel(self.groupBox_4)
        self.label_30.setGeometry(QtCore.QRect(340, 560, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_31 = QtWidgets.QLabel(self.groupBox_4)
        self.label_31.setGeometry(QtCore.QRect(120, 500, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.label_70 = QtWidgets.QLabel(self.groupBox_4)
        self.label_70.setGeometry(QtCore.QRect(170, 30, 81, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_70.setFont(font)
        self.label_70.setAlignment(QtCore.Qt.AlignCenter)
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.label_71 = QtWidgets.QLabel(self.groupBox_4)
        self.label_71.setGeometry(QtCore.QRect(350, 30, 81, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_71.setFont(font)
        self.label_71.setAlignment(QtCore.Qt.AlignCenter)
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.label_72 = QtWidgets.QLabel(self.groupBox_4)
        self.label_72.setGeometry(QtCore.QRect(20, 50, 100, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_72.sizePolicy().hasHeightForWidth())
        self.label_72.setSizePolicy(sizePolicy)
        self.label_72.setMinimumSize(QtCore.QSize(100, 100))
        self.label_72.setMaximumSize(QtCore.QSize(100, 100))
        self.label_72.setText(_fromUtf8(""))
        self.label_72.setPixmap(QtGui.QPixmap(_fromUtf8("heading.png")))
        self.label_72.setAlignment(QtCore.Qt.AlignCenter)
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.label_73 = QtWidgets.QLabel(self.groupBox_4)
        self.label_73.setGeometry(QtCore.QRect(190, 50, 100, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_73.sizePolicy().hasHeightForWidth())
        self.label_73.setSizePolicy(sizePolicy)
        self.label_73.setText(_fromUtf8(""))
        self.label_73.setPixmap(QtGui.QPixmap(_fromUtf8("roll.png")))
        self.label_73.setAlignment(QtCore.Qt.AlignCenter)
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.label_74 = QtWidgets.QLabel(self.groupBox_4)
        self.label_74.setGeometry(QtCore.QRect(360, 50, 100, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_74.sizePolicy().hasHeightForWidth())
        self.label_74.setSizePolicy(sizePolicy)
        self.label_74.setText(_fromUtf8(""))
        self.label_74.setPixmap(QtGui.QPixmap(_fromUtf8("pitch.png")))
        self.label_74.setAlignment(QtCore.Qt.AlignCenter)
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.label_75 = QtWidgets.QLabel(self.groupBox_4)
        self.label_75.setGeometry(QtCore.QRect(30, 150, 81, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_75.setFont(font)
        self.label_75.setAlignment(QtCore.Qt.AlignCenter)
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.label_76 = QtWidgets.QLabel(self.groupBox_4)
        self.label_76.setGeometry(QtCore.QRect(200, 150, 81, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_76.setFont(font)
        self.label_76.setAlignment(QtCore.Qt.AlignCenter)
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.label_77 = QtWidgets.QLabel(self.groupBox_4)
        self.label_77.setGeometry(QtCore.QRect(370, 150, 81, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_77.setFont(font)
        self.label_77.setAlignment(QtCore.Qt.AlignCenter)
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 390, 781, 221))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_5)
        self.textEdit.setGeometry(QtCore.QRect(20, 40, 721, 171))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textEdit.setFont(font)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.label_50 = QtWidgets.QLabel(self.tab)
        self.label_50.setGeometry(QtCore.QRect(160, 600, 181, 21))
        self.label_50.setStyleSheet(_fromUtf8("color:rgb(0, 0, 255)"))
        self.label_50.setAlignment(QtCore.Qt.AlignCenter)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.label_51 = QtWidgets.QLabel(self.tab)
        self.label_51.setGeometry(QtCore.QRect(300, 600, 181, 21))
        self.label_51.setStyleSheet(_fromUtf8("color:rgb(255, 170, 0)"))
        self.label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.label_52 = QtWidgets.QLabel(self.tab)
        self.label_52.setGeometry(QtCore.QRect(450, 600, 181, 21))
        self.label_52.setStyleSheet(_fromUtf8("color:rgb(255, 0, 0)"))
        self.label_52.setAlignment(QtCore.Qt.AlignCenter)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.label_53 = QtWidgets.QLabel(self.tab)
        self.label_53.setGeometry(QtCore.QRect(20, 600, 181, 21))
        self.label_53.setStyleSheet(_fromUtf8("color:rgb(85, 170, 0)"))
        self.label_53.setAlignment(QtCore.Qt.AlignCenter)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_9.setGeometry(QtCore.QRect(390, 190, 371, 151))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.label_44 = QtWidgets.QLabel(self.groupBox_9)
        self.label_44.setGeometry(QtCore.QRect(40, 60, 151, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_44.setFont(font)
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.label_48 = QtWidgets.QLabel(self.groupBox_9)
        self.label_48.setGeometry(QtCore.QRect(40, 30, 141, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_48.setFont(font)
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.progressBar = QtWidgets.QProgressBar(self.groupBox_9)
        self.progressBar.setGeometry(QtCore.QRect(230, 30, 118, 23))
        self.progressBar.setMinimum(1400)
        self.progressBar.setMaximum(2500)
        self.progressBar.setProperty("value", 1500)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.progressBar_2 = QtWidgets.QProgressBar(self.groupBox_9)
        self.progressBar_2.setGeometry(QtCore.QRect(230, 60, 118, 23))
        self.progressBar_2.setMinimum(1400)
        self.progressBar_2.setMaximum(2500)
        self.progressBar_2.setProperty("value", 1500)
        self.progressBar_2.setObjectName(_fromUtf8("progressBar_2"))
        self.label_79 = QtWidgets.QLabel(self.tab)
        self.label_79.setGeometry(QtCore.QRect(590, 600, 181, 21))
        self.label_79.setStyleSheet(_fromUtf8("color:rgb(170, 0, 0)"))
        self.label_79.setAlignment(QtCore.Qt.AlignCenter)
        self.label_79.setObjectName(_fromUtf8("label_79"))
        self.groupBox_4.raise_()
        self.groupBox.raise_()
        self.groupBox_2.raise_()
        self.groupBox_3.raise_()
        self.groupBox_5.raise_()
        self.label_50.raise_()
        self.label_51.raise_()
        self.label_52.raise_()
        self.label_53.raise_()
        self.groupBox_9.raise_()
        self.label_79.raise_()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/noun_dashboard_357677.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon1, _fromUtf8(""))
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 60, 441, 171))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.label_38 = QtWidgets.QLabel(self.groupBox_6)
        self.label_38.setGeometry(QtCore.QRect(10, 40, 181, 21))
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.label_39 = QtWidgets.QLabel(self.groupBox_6)
        self.label_39.setGeometry(QtCore.QRect(10, 70, 181, 21))
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.label_40 = QtWidgets.QLabel(self.groupBox_6)
        self.label_40.setGeometry(QtCore.QRect(10, 100, 181, 21))
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.label_41 = QtWidgets.QLabel(self.groupBox_6)
        self.label_41.setGeometry(QtCore.QRect(230, 40, 121, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setStyleSheet(_fromUtf8("color:rgb(255, 0, 0)"))
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.comboBox = QtWidgets.QComboBox(self.groupBox_6)
        self.comboBox.setGeometry(QtCore.QRect(230, 100, 181, 27))
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_6)
        self.comboBox_2.setGeometry(QtCore.QRect(230, 70, 181, 27))
        self.comboBox_2.setEditable(True)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.pushButton = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton.setGeometry(QtCore.QRect(230, 130, 181, 27))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_7.setEnabled(True)
        self.pushButton_7.setGeometry(QtCore.QRect(40, 130, 121, 27))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 250, 441, 131))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.label_42 = QtWidgets.QLabel(self.groupBox_7)
        self.label_42.setGeometry(QtCore.QRect(10, 40, 181, 21))
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.label_43 = QtWidgets.QLabel(self.groupBox_7)
        self.label_43.setGeometry(QtCore.QRect(10, 70, 181, 21))
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.label_45 = QtWidgets.QLabel(self.groupBox_7)
        self.label_45.setGeometry(QtCore.QRect(230, 40, 181, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setStyleSheet(_fromUtf8("color:rgb(255, 0, 0)"))
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBox_4.setGeometry(QtCore.QRect(230, 70, 181, 27))
        self.comboBox_4.setEditable(True)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 100, 181, 27))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_8.setGeometry(QtCore.QRect(40, 100, 121, 27))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 410, 441, 171))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.label_46 = QtWidgets.QLabel(self.groupBox_8)
        self.label_46.setGeometry(QtCore.QRect(10, 40, 181, 21))
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.label_47 = QtWidgets.QLabel(self.groupBox_8)
        self.label_47.setGeometry(QtCore.QRect(10, 70, 181, 21))
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.label_49 = QtWidgets.QLabel(self.groupBox_8)
        self.label_49.setGeometry(QtCore.QRect(230, 40, 181, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setStyleSheet(_fromUtf8("color:rgb(255, 0, 0)"))
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.comboBox_6 = QtWidgets.QComboBox(self.groupBox_8)
        self.comboBox_6.setGeometry(QtCore.QRect(230, 70, 181, 27))
        self.comboBox_6.setEditable(True)
        self.comboBox_6.setObjectName(_fromUtf8("comboBox_6"))
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_3.setGeometry(QtCore.QRect(230, 100, 181, 27))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_9.setGeometry(QtCore.QRect(40, 100, 121, 27))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/noun_connection_1583671.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_2, icon2, _fromUtf8(""))
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.graphicsView_3 = QOSM(self.tab_3)
        self.graphicsView_3.setGeometry(QtCore.QRect(10, 10, 1251, 621))
        self.graphicsView_3.setObjectName(_fromUtf8("graphicsView_3"))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/noun_Map_972135.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_3, icon3, _fromUtf8(""))
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.graphicsView_6 = PlotWidget(self.tab_4)
        self.graphicsView_6.setGeometry(QtCore.QRect(40, 471, 581, 141))
        self.graphicsView_6.setObjectName(_fromUtf8("graphicsView_6"))
        self.graphicsView_7 = PlotWidget(self.tab_4)
        self.graphicsView_7.setGeometry(QtCore.QRect(40, 260, 581, 141))
        self.graphicsView_7.setObjectName(_fromUtf8("graphicsView_7"))
        self.graphicsView_8 = PlotWidget(self.tab_4)
        self.graphicsView_8.setGeometry(QtCore.QRect(40, 60, 581, 141))
        self.graphicsView_8.setObjectName(_fromUtf8("graphicsView_8"))
        self.graphicsView_9 = PlotWidget(self.tab_4)
        self.graphicsView_9.setGeometry(QtCore.QRect(650, 59, 581, 141))
        self.graphicsView_9.setObjectName(_fromUtf8("graphicsView_9"))
        self.graphicsView_11 = PlotWidget(self.tab_4)
        self.graphicsView_11.setGeometry(QtCore.QRect(650, 470, 581, 141))
        self.graphicsView_11.setObjectName(_fromUtf8("graphicsView_11"))
        self.label_32 = QtWidgets.QLabel(self.tab_4)
        self.label_32.setGeometry(QtCore.QRect(40, 40, 581, 20))
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.label_33 = QtWidgets.QLabel(self.tab_4)
        self.label_33.setGeometry(QtCore.QRect(650, 40, 581, 17))
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.label_34 = QtWidgets.QLabel(self.tab_4)
        self.label_34.setGeometry(QtCore.QRect(40, 240, 581, 20))
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.label_36 = QtWidgets.QLabel(self.tab_4)
        self.label_36.setGeometry(QtCore.QRect(40, 450, 581, 20))
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.label_37 = QtWidgets.QLabel(self.tab_4)
        self.label_37.setGeometry(QtCore.QRect(650, 450, 581, 17))
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.graphicsView_10 = PlotWidget(self.tab_4)
        self.graphicsView_10.setGeometry(QtCore.QRect(650, 259, 581, 141))
        self.graphicsView_10.setObjectName(_fromUtf8("graphicsView_10"))
        self.label_35 = QtWidgets.QLabel(self.tab_4)
        self.label_35.setGeometry(QtCore.QRect(650, 240, 581, 17))
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/noun_Graph_1495300.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_4, icon4, _fromUtf8(""))
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_10.setGeometry(QtCore.QRect(20, 30, 481, 241))
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.verticalSlider = QtWidgets.QSlider(self.groupBox_10)
        self.verticalSlider.setGeometry(QtCore.QRect(80, 60, 29, 171))
        self.verticalSlider.setMaximum(3)
        self.verticalSlider.setPageStep(1)
        self.verticalSlider.setSliderPosition(0)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setInvertedAppearance(False)
        self.verticalSlider.setObjectName(_fromUtf8("verticalSlider"))
        self.label_60 = QtWidgets.QLabel(self.groupBox_10)
        self.label_60.setGeometry(QtCore.QRect(120, 161, 131, 17))
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.label_61 = QtWidgets.QLabel(self.groupBox_10)
        self.label_61.setGeometry(QtCore.QRect(120, 111, 131, 17))
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.label_62 = QtWidgets.QLabel(self.groupBox_10)
        self.label_62.setGeometry(QtCore.QRect(120, 61, 161, 17))
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.label_63 = QtWidgets.QLabel(self.groupBox_10)
        self.label_63.setGeometry(QtCore.QRect(120, 210, 161, 17))
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_4.setGeometry(QtCore.QRect(370, 60, 99, 27))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.label_64 = QtWidgets.QLabel(self.groupBox_10)
        self.label_64.setGeometry(QtCore.QRect(270, 110, 91, 20))
        self.label_64.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.label_65 = QtWidgets.QLabel(self.groupBox_10)
        self.label_65.setGeometry(QtCore.QRect(260, 160, 101, 20))
        self.label_65.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_10)
        self.doubleSpinBox.setGeometry(QtCore.QRect(368, 110, 101, 27))
        self.doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.doubleSpinBox.setProperty("value", 3.0)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.groupBox_10)
        self.doubleSpinBox_2.setGeometry(QtCore.QRect(370, 160, 101, 27))
        self.doubleSpinBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.doubleSpinBox_2.setProperty("value", 5.0)
        self.doubleSpinBox_2.setObjectName(_fromUtf8("doubleSpinBox_2"))
        self.label_90 = QtWidgets.QLabel(self.groupBox_10)
        self.label_90.setGeometry(QtCore.QRect(0, 40, 81, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_90.setFont(font)
        self.label_90.setAlignment(QtCore.Qt.AlignCenter)
        self.label_90.setObjectName(_fromUtf8("label_90"))
        self.label_91 = QtWidgets.QLabel(self.groupBox_10)
        self.label_91.setGeometry(QtCore.QRect(10, 60, 71, 17))
        self.label_91.setAlignment(QtCore.Qt.AlignCenter)
        self.label_91.setObjectName(_fromUtf8("label_91"))
        self.label_92 = QtWidgets.QLabel(self.groupBox_10)
        self.label_92.setGeometry(QtCore.QRect(10, 110, 71, 17))
        self.label_92.setAlignment(QtCore.Qt.AlignCenter)
        self.label_92.setObjectName(_fromUtf8("label_92"))
        self.label_95 = QtWidgets.QLabel(self.groupBox_10)
        self.label_95.setGeometry(QtCore.QRect(10, 160, 71, 17))
        self.label_95.setAlignment(QtCore.Qt.AlignCenter)
        self.label_95.setObjectName(_fromUtf8("label_95"))
        self.label_96 = QtWidgets.QLabel(self.groupBox_10)
        self.label_96.setGeometry(QtCore.QRect(10, 210, 71, 20))
        self.label_96.setAlignment(QtCore.Qt.AlignCenter)
        self.label_96.setObjectName(_fromUtf8("label_96"))
        self.label_97 = QtWidgets.QLabel(self.groupBox_10)
        self.label_97.setGeometry(QtCore.QRect(120, 40, 151, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_97.setFont(font)
        self.label_97.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_97.setObjectName(_fromUtf8("label_97"))
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_11.setGeometry(QtCore.QRect(520, 30, 151, 241))
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.label_59 = QtWidgets.QLabel(self.groupBox_11)
        self.label_59.setGeometry(QtCore.QRect(30, 190, 31, 17))
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.label_58 = QtWidgets.QLabel(self.groupBox_11)
        self.label_58.setGeometry(QtCore.QRect(20, 140, 111, 17))
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.label_55 = QtWidgets.QLabel(self.groupBox_11)
        self.label_55.setGeometry(QtCore.QRect(80, 100, 31, 17))
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.label_57 = QtWidgets.QLabel(self.groupBox_11)
        self.label_57.setGeometry(QtCore.QRect(80, 190, 31, 17))
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.horizontalSlider_2 = QtWidgets.QSlider(self.groupBox_11)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(30, 160, 71, 29))
        self.horizontalSlider_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.horizontalSlider_2.setMaximum(1)
        self.horizontalSlider_2.setPageStep(1)
        self.horizontalSlider_2.setProperty("value", 1)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName(_fromUtf8("horizontalSlider_2"))
        self.label_56 = QtWidgets.QLabel(self.groupBox_11)
        self.label_56.setGeometry(QtCore.QRect(20, 50, 111, 17))
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox_11)
        self.horizontalSlider.setGeometry(QtCore.QRect(30, 70, 71, 29))
        self.horizontalSlider.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.horizontalSlider.setMaximum(1)
        self.horizontalSlider.setPageStep(1)
        self.horizontalSlider.setProperty("value", 1)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.label_54 = QtWidgets.QLabel(self.groupBox_11)
        self.label_54.setGeometry(QtCore.QRect(30, 100, 31, 17))
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_12.setGeometry(QtCore.QRect(680, 30, 581, 591))
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.graphicsView_13 = PlotWidget(self.groupBox_12)
        self.graphicsView_13.setGeometry(QtCore.QRect(30, 40, 541, 541))
        self.graphicsView_13.setObjectName(_fromUtf8("graphicsView_13"))
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_13.setGeometry(QtCore.QRect(20, 370, 681, 251))
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.textEdit_2 = QtWidgets.QTextEdit(self.groupBox_13)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 30, 641, 201))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setReadOnly(True)
        self.textEdit_2.setObjectName(_fromUtf8("textEdit_2"))
        self.label_66 = QtWidgets.QLabel(self.groupBox_13)
        self.label_66.setGeometry(QtCore.QRect(100, 230, 181, 21))
        self.label_66.setStyleSheet(_fromUtf8("color:rgb(0, 0, 255)"))
        self.label_66.setAlignment(QtCore.Qt.AlignCenter)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.label_67 = QtWidgets.QLabel(self.groupBox_13)
        self.label_67.setGeometry(QtCore.QRect(-30, 230, 181, 21))
        self.label_67.setStyleSheet(_fromUtf8("color:rgb(85, 170, 0)"))
        self.label_67.setAlignment(QtCore.Qt.AlignCenter)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.label_80 = QtWidgets.QLabel(self.groupBox_13)
        self.label_80.setGeometry(QtCore.QRect(510, 230, 181, 21))
        self.label_80.setStyleSheet(_fromUtf8("color:rgb(170, 0, 0)"))
        self.label_80.setAlignment(QtCore.Qt.AlignCenter)
        self.label_80.setObjectName(_fromUtf8("label_80"))
        self.label_68 = QtWidgets.QLabel(self.groupBox_13)
        self.label_68.setGeometry(QtCore.QRect(240, 230, 181, 21))
        self.label_68.setStyleSheet(_fromUtf8("color:rgb(255, 170, 0)"))
        self.label_68.setAlignment(QtCore.Qt.AlignCenter)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.label_69 = QtWidgets.QLabel(self.groupBox_13)
        self.label_69.setGeometry(QtCore.QRect(380, 230, 181, 21))
        self.label_69.setStyleSheet(_fromUtf8("color:rgb(255, 0, 0)"))
        self.label_69.setAlignment(QtCore.Qt.AlignCenter)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_5.setEnabled(True)
        self.pushButton_5.setGeometry(QtCore.QRect(160, 280, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet(_fromUtf8("color:rgb(0, 170, 0)"))
        self.pushButton_5.setCheckable(False)
        self.pushButton_5.setChecked(False)
        self.pushButton_5.setAutoRepeat(False)
        self.pushButton_5.setAutoDefault(False)
        self.pushButton_5.setDefault(False)
        self.pushButton_5.setFlat(False)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_6.setGeometry(QtCore.QRect(330, 280, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet(_fromUtf8("color:rgb(255, 0, 0)"))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.label_78 = QtWidgets.QLabel(self.tab_5)
        self.label_78.setGeometry(QtCore.QRect(710, 610, 541, 20))
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_78.setFont(font)
        self.label_78.setAlignment(QtCore.Qt.AlignCenter)
        self.label_78.setObjectName(_fromUtf8("label_78"))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/noun_sequence_121702.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_5, icon5, _fromUtf8(""))
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.groupBox_14 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_14.setGeometry(QtCore.QRect(20, 30, 611, 151))
        self.groupBox_14.setObjectName(_fromUtf8("groupBox_14"))
        self.label_81 = QtWidgets.QLabel(self.groupBox_14)
        self.label_81.setGeometry(QtCore.QRect(10, 50, 61, 21))
        self.label_81.setAlignment(QtCore.Qt.AlignCenter)
        self.label_81.setObjectName(_fromUtf8("label_81"))
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.groupBox_14)
        self.doubleSpinBox_3.setGeometry(QtCore.QRect(90, 50, 111, 27))
        self.doubleSpinBox_3.setDecimals(4)
        self.doubleSpinBox_3.setObjectName(_fromUtf8("doubleSpinBox_3"))
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.groupBox_14)
        self.doubleSpinBox_4.setGeometry(QtCore.QRect(90, 80, 111, 27))
        self.doubleSpinBox_4.setDecimals(4)
        self.doubleSpinBox_4.setObjectName(_fromUtf8("doubleSpinBox_4"))
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.groupBox_14)
        self.doubleSpinBox_5.setGeometry(QtCore.QRect(90, 110, 111, 27))
        self.doubleSpinBox_5.setDecimals(4)
        self.doubleSpinBox_5.setObjectName(_fromUtf8("doubleSpinBox_5"))
        self.label_82 = QtWidgets.QLabel(self.groupBox_14)
        self.label_82.setGeometry(QtCore.QRect(10, 80, 61, 21))
        self.label_82.setAlignment(QtCore.Qt.AlignCenter)
        self.label_82.setObjectName(_fromUtf8("label_82"))
        self.label_83 = QtWidgets.QLabel(self.groupBox_14)
        self.label_83.setGeometry(QtCore.QRect(10, 110, 61, 21))
        self.label_83.setAlignment(QtCore.Qt.AlignCenter)
        self.label_83.setObjectName(_fromUtf8("label_83"))
        self.label_84 = QtWidgets.QLabel(self.groupBox_14)
        self.label_84.setGeometry(QtCore.QRect(310, 80, 61, 21))
        self.label_84.setAlignment(QtCore.Qt.AlignCenter)
        self.label_84.setObjectName(_fromUtf8("label_84"))
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(self.groupBox_14)
        self.doubleSpinBox_6.setGeometry(QtCore.QRect(390, 80, 111, 27))
        self.doubleSpinBox_6.setDecimals(4)
        self.doubleSpinBox_6.setObjectName(_fromUtf8("doubleSpinBox_6"))
        self.label_85 = QtWidgets.QLabel(self.groupBox_14)
        self.label_85.setGeometry(QtCore.QRect(310, 50, 61, 21))
        self.label_85.setAlignment(QtCore.Qt.AlignCenter)
        self.label_85.setObjectName(_fromUtf8("label_85"))
        self.doubleSpinBox_7 = QtWidgets.QDoubleSpinBox(self.groupBox_14)
        self.doubleSpinBox_7.setGeometry(QtCore.QRect(390, 110, 111, 27))
        self.doubleSpinBox_7.setDecimals(4)
        self.doubleSpinBox_7.setObjectName(_fromUtf8("doubleSpinBox_7"))
        self.label_86 = QtWidgets.QLabel(self.groupBox_14)
        self.label_86.setGeometry(QtCore.QRect(310, 110, 61, 21))
        self.label_86.setAlignment(QtCore.Qt.AlignCenter)
        self.label_86.setObjectName(_fromUtf8("label_86"))
        self.doubleSpinBox_8 = QtWidgets.QDoubleSpinBox(self.groupBox_14)
        self.doubleSpinBox_8.setGeometry(QtCore.QRect(390, 50, 111, 27))
        self.doubleSpinBox_8.setDecimals(4)
        self.doubleSpinBox_8.setObjectName(_fromUtf8("doubleSpinBox_8"))
        self.label_93 = QtWidgets.QLabel(self.groupBox_14)
        self.label_93.setGeometry(QtCore.QRect(20, 30, 181, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_93.setFont(font)
        self.label_93.setStyleSheet(_fromUtf8(""))
        self.label_93.setAlignment(QtCore.Qt.AlignCenter)
        self.label_93.setObjectName(_fromUtf8("label_93"))
        self.label_94 = QtWidgets.QLabel(self.groupBox_14)
        self.label_94.setGeometry(QtCore.QRect(320, 30, 201, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_94.setFont(font)
        self.label_94.setStyleSheet(_fromUtf8(""))
        self.label_94.setAlignment(QtCore.Qt.AlignCenter)
        self.label_94.setObjectName(_fromUtf8("label_94"))
        self.groupBox_15 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_15.setGeometry(QtCore.QRect(650, 30, 611, 151))
        self.groupBox_15.setObjectName(_fromUtf8("groupBox_15"))
        self.label_87 = QtWidgets.QLabel(self.groupBox_15)
        self.label_87.setGeometry(QtCore.QRect(30, 80, 61, 21))
        self.label_87.setAlignment(QtCore.Qt.AlignCenter)
        self.label_87.setObjectName(_fromUtf8("label_87"))
        self.label_88 = QtWidgets.QLabel(self.groupBox_15)
        self.label_88.setGeometry(QtCore.QRect(30, 110, 61, 21))
        self.label_88.setAlignment(QtCore.Qt.AlignCenter)
        self.label_88.setObjectName(_fromUtf8("label_88"))
        self.label_89 = QtWidgets.QLabel(self.groupBox_15)
        self.label_89.setGeometry(QtCore.QRect(30, 50, 61, 21))
        self.label_89.setAlignment(QtCore.Qt.AlignCenter)
        self.label_89.setObjectName(_fromUtf8("label_89"))
        self.doubleSpinBox_9 = QtWidgets.QDoubleSpinBox(self.groupBox_15)
        self.doubleSpinBox_9.setGeometry(QtCore.QRect(110, 110, 111, 27))
        self.doubleSpinBox_9.setDecimals(4)
        self.doubleSpinBox_9.setObjectName(_fromUtf8("doubleSpinBox_9"))
        self.doubleSpinBox_10 = QtWidgets.QDoubleSpinBox(self.groupBox_15)
        self.doubleSpinBox_10.setGeometry(QtCore.QRect(110, 80, 111, 27))
        self.doubleSpinBox_10.setDecimals(4)
        self.doubleSpinBox_10.setObjectName(_fromUtf8("doubleSpinBox_10"))
        self.doubleSpinBox_11 = QtWidgets.QDoubleSpinBox(self.groupBox_15)
        self.doubleSpinBox_11.setGeometry(QtCore.QRect(110, 50, 111, 27))
        self.doubleSpinBox_11.setDecimals(4)
        self.doubleSpinBox_11.setObjectName(_fromUtf8("doubleSpinBox_11"))
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_10.setEnabled(False)
        self.pushButton_10.setGeometry(QtCore.QRect(400, 590, 181, 27))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_11.setEnabled(False)
        self.pushButton_11.setGeometry(QtCore.QRect(600, 590, 181, 27))
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/noun_configuration_1613324.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_6, icon6, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1280, 25))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuCeres_GUI = QtWidgets.QMenu(self.menuBar)
        self.menuCeres_GUI.setObjectName(_fromUtf8("menuCeres_GUI"))
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuCeres_GUI.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuCeres_GUI.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "CERES GUI", None))
        self.groupBox.setTitle(_translate("MainWindow", "RC Channels Overview", None))
        self.label.setText(_translate("MainWindow", "Throttle", None))
        self.progressBarYaw.setFormat(_translate("MainWindow", "%v%", None))
        self.label_2.setText(_translate("MainWindow", "Yaw Speed", None))
        self.label_3.setText(_translate("MainWindow", "AUX", None))
        self.label_4.setText(_translate("MainWindow", "Emergency", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Connexions Overview", None))
        self.label_5.setText(_translate("MainWindow", "IMU Connexion", None))
        self.label_6.setText(_translate("MainWindow", "Arduino RC Connexion", None))
        self.label_7.setText(_translate("MainWindow", "Main Arduino Connexion", None))
        self.label_8.setText(_translate("MainWindow", "Not Connected", None))
        self.label_9.setText(_translate("MainWindow", "Not Connected", None))
        self.label_10.setText(_translate("MainWindow", "Not Connected", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Robot Status", None))
        self.label_11.setText(_translate("MainWindow", "Mode", None))
        self.label_12.setText(_translate("MainWindow", "Emergency Stop", None))
        self.label_13.setText(_translate("MainWindow", "Drivers Brakes", None))
        self.label_14.setText(_translate("MainWindow", "EM Brakes", None))
        self.label_23.setText(_translate("MainWindow", "Cooling Pumps", None))
        self.label_24.setText(_translate("MainWindow", "Desactivated", None))
        self.label_25.setText(_translate("MainWindow", "Desactivated", None))
        self.label_26.setText(_translate("MainWindow", "Desactivated", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Robot Position", None))
        self.label_15.setText(_translate("MainWindow", "Heading", None))
        self.label_16.setText(_translate("MainWindow", "Map Position", None))
        self.label_17.setText(_translate("MainWindow", "Latitude:", None))
        self.label_18.setText(_translate("MainWindow", "Longitude: ", None))
        self.label_19.setText(_translate("MainWindow", "Position to Origin:", None))
        self.label_20.setText(_translate("MainWindow", "Northing:", None))
        self.label_21.setText(_translate("MainWindow", "Easting:", None))
        self.label_22.setText(_translate("MainWindow", "Altitude:", None))
        self.label_27.setText(_translate("MainWindow", "48.856614", None))
        self.label_28.setText(_translate("MainWindow", "2.3522219", None))
        self.label_29.setText(_translate("MainWindow", "15.65m", None))
        self.label_30.setText(_translate("MainWindow", "172.6m", None))
        self.label_31.setText(_translate("MainWindow", "2300m", None))
        self.label_70.setText(_translate("MainWindow", "Roll", None))
        self.label_71.setText(_translate("MainWindow", "Pitch", None))
        self.label_75.setText(_translate("MainWindow", "180°", None))
        self.label_76.setText(_translate("MainWindow", "180°", None))
        self.label_77.setText(_translate("MainWindow", "180°", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Terminal Messages", None))
        self.label_50.setText(_translate("MainWindow", "Info Messages", None))
        self.label_51.setText(_translate("MainWindow", "Warning Messages", None))
        self.label_52.setText(_translate("MainWindow", "Error Messages", None))
        self.label_53.setText(_translate("MainWindow", "Debug Messages", None))
        self.groupBox_9.setTitle(_translate("MainWindow", "Drivers Overview", None))
        self.label_44.setText(_translate("MainWindow", "Right Driver Voltage", None))
        self.label_48.setText(_translate("MainWindow", "Left Driver Voltage", None))
        self.progressBar.setFormat(_translate("MainWindow", "%v mV", None))
        self.progressBar_2.setFormat(_translate("MainWindow", "%v mV", None))
        self.label_79.setText(_translate("MainWindow", "Fatal Messages", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Robot Overview", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "IMU", None))
        self.label_38.setText(_translate("MainWindow", "IMU Connexion", None))
        self.label_39.setText(_translate("MainWindow", "Serial Port", None))
        self.label_40.setText(_translate("MainWindow", "Serial Velocity", None))
        self.label_41.setText(_translate("MainWindow", "Not Connected", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "115200", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "1200", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "2400", None))
        self.comboBox.setItemText(3, _translate("MainWindow", "4800", None))
        self.comboBox.setItemText(4, _translate("MainWindow", "9600", None))
        self.comboBox.setItemText(5, _translate("MainWindow", "19200", None))
        self.comboBox.setItemText(6, _translate("MainWindow", "38400", None))
        self.comboBox.setItemText(7, _translate("MainWindow", "57600", None))
        self.comboBox.setItemText(8, _translate("MainWindow", "230400", None))
        self.comboBox.setItemText(9, _translate("MainWindow", "250000", None))
        self.comboBox.setItemText(10, _translate("MainWindow", "460800", None))
        self.comboBox.setItemText(11, _translate("MainWindow", "500000", None))
        self.comboBox.setItemText(12, _translate("MainWindow", "800000", None))
        self.comboBox.setItemText(13, _translate("MainWindow", "921600", None))
        self.comboBox.setItemText(14, _translate("MainWindow", "1000000", None))
        self.comboBox.setItemText(15, _translate("MainWindow", "2000000", None))
        self.pushButton.setText(_translate("MainWindow", "Connect", None))
        self.pushButton_7.setText(_translate("MainWindow", "Auto-Detect", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Arduino RC", None))
        self.label_42.setText(_translate("MainWindow", "Arduino RC Connexion", None))
        self.label_43.setText(_translate("MainWindow", "Serial Port", None))
        self.label_45.setText(_translate("MainWindow", "Not Connected", None))
        self.pushButton_2.setText(_translate("MainWindow", "Connect", None))
        self.pushButton_8.setText(_translate("MainWindow", "Auto-Detect", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Main Arduino", None))
        self.label_46.setText(_translate("MainWindow", "Main Arduino Connexion", None))
        self.label_47.setText(_translate("MainWindow", "Serial Port", None))
        self.label_49.setText(_translate("MainWindow", "Not Connected", None))
        self.pushButton_3.setText(_translate("MainWindow", "Connect", None))
        self.pushButton_9.setText(_translate("MainWindow", "Auto-Detect", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Connections", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "GPS / Map", None))
        self.label_32.setText(_translate("MainWindow", "Easting Position [m]", None))
        self.label_33.setText(_translate("MainWindow", "Robot X Velocity [m/s]", None))
        self.label_34.setText(_translate("MainWindow", "Northing Position [m]", None))
        self.label_36.setText(_translate("MainWindow", "Heading Orientation [deg]", None))
        self.label_37.setText(_translate("MainWindow", "Robot Angular Velocity [rad/s]", None))
        self.label_35.setText(_translate("MainWindow", "Robot Y Velocity [m/s]", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Sensors", None))
        self.groupBox_10.setTitle(_translate("MainWindow", "Trajectory Options", None))
        self.label_60.setText(_translate("MainWindow", "Circular Trajectory", None))
        self.label_61.setText(_translate("MainWindow", "Linear Trajectory", None))
        self.label_62.setText(_translate("MainWindow", "Custom CSV Trajectory", None))
        self.label_63.setText(_translate("MainWindow", "Manual Trajectory", None))
        self.pushButton_4.setText(_translate("MainWindow", "Open File...", None))
        self.label_64.setText(_translate("MainWindow", "Distance [m]:", None))
        self.label_65.setText(_translate("MainWindow", "Diameter [m]:", None))
        self.label_90.setText(_translate("MainWindow", "Controller", None))
        self.label_91.setText(_translate("MainWindow", "Pose", None))
        self.label_92.setText(_translate("MainWindow", "Vel", None))
        self.label_95.setText(_translate("MainWindow", "Vel", None))
        self.label_96.setText(_translate("MainWindow", "Custom", None))
        self.label_97.setText(_translate("MainWindow", "Trajectory Selection", None))
        self.groupBox_11.setTitle(_translate("MainWindow", "Recording Options", None))
        self.label_59.setText(_translate("MainWindow", "ON", None))
        self.label_58.setText(_translate("MainWindow", "BAG Recording", None))
        self.label_55.setText(_translate("MainWindow", "OFF", None))
        self.label_57.setText(_translate("MainWindow", "OFF", None))
        self.label_56.setText(_translate("MainWindow", "CSV Recording", None))
        self.label_54.setText(_translate("MainWindow", "ON", None))
        self.groupBox_12.setTitle(_translate("MainWindow", "Movement Previews", None))
        self.groupBox_13.setTitle(_translate("MainWindow", "Terminal Messages", None))
        self.label_66.setText(_translate("MainWindow", "Info Messages", None))
        self.label_67.setText(_translate("MainWindow", "Debug Messages", None))
        self.label_80.setText(_translate("MainWindow", "Fatal Messages", None))
        self.label_68.setText(_translate("MainWindow", "Warning Messages", None))
        self.label_69.setText(_translate("MainWindow", "Error Messages", None))
        self.pushButton_5.setText(_translate("MainWindow", "START", None))
        self.pushButton_6.setText(_translate("MainWindow", "STOP", None))
        self.label_78.setText(_translate("MainWindow", "Representation in the CERES Referential: X=Right, Y=Front", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Test Sequences", None))
        self.groupBox_14.setTitle(_translate("MainWindow", "Low-Level Speed Controller (PID)", None))
        self.label_81.setText(_translate("MainWindow", "Kp", None))
        self.label_82.setText(_translate("MainWindow", "Ki", None))
        self.label_83.setText(_translate("MainWindow", "Kd", None))
        self.label_84.setText(_translate("MainWindow", "Ki", None))
        self.label_85.setText(_translate("MainWindow", "Kp", None))
        self.label_86.setText(_translate("MainWindow", "Kd", None))
        self.label_93.setText(_translate("MainWindow", "Linear Speed U [m/s]", None))
        self.label_94.setText(_translate("MainWindow", "Rotational Speed W [rad/s]", None))
        self.groupBox_15.setTitle(_translate("MainWindow", "High-Level Position Controller", None))
        self.label_87.setText(_translate("MainWindow", "Ki", None))
        self.label_88.setText(_translate("MainWindow", "Kd", None))
        self.label_89.setText(_translate("MainWindow", "Kp", None))
        self.pushButton_10.setText(_translate("MainWindow", "Read Values", None))
        self.pushButton_11.setText(_translate("MainWindow", "Write Values", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Configuration", None))
        self.menuCeres_GUI.setTitle(_translate("MainWindow", "Ceres GUI", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))

from pyqtgraph import PlotWidget
from qOSM.common import QOSM
import ressources_rc
