# -*- coding: utf-8 -*-
from PyQt5 import QtWidgets, QtGui, QtCore
from pyqtgraph import PlotWidget

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class TabCeres(object):

	try:
		def _fromUtf8(self, s):
			return QtCore.QString.fromUtf8(s)
	except AttributeError:
		def _fromUtf8(self, s):
			return s

	def __init__(self):
		self.tab = QtWidgets.QWidget()
		self.tab.setObjectName(self._fromUtf8("tab"))
		self.label_3 = QtWidgets.QLabel(self.tab)
		self.label_3.setGeometry(QtCore.QRect(90, 490, 161, 21))
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		self.label_3.setFont(font)
		self.label_3.setObjectName(self._fromUtf8("label_3"))
		self.label_11 = QtWidgets.QLabel(self.tab)
		self.label_11.setGeometry(QtCore.QRect(140, 750, 81, 21))
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		self.label_11.setFont(font)
		self.label_11.setObjectName(self._fromUtf8("label_11"))
		self.label_14 = QtWidgets.QLabel(self.tab)
		self.label_14.setGeometry(QtCore.QRect(140, 710, 81, 21))
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		self.label_14.setFont(font)
		self.label_14.setObjectName(self._fromUtf8("label_14"))
		self.label_17 = QtWidgets.QLabel(self.tab)
		self.label_17.setGeometry(QtCore.QRect(250, 600, 81, 21))
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		self.label_17.setFont(font)
		self.label_17.setObjectName(self._fromUtf8("label_17"))
		self.graphicsView_4 = PlotWidget(self.tab)
		self.graphicsView_4.setGeometry(QtCore.QRect(490, 290, 771, 261))
		self.graphicsView_4.setObjectName(self._fromUtf8("graphicsView_4"))
		self.label_15 = QtWidgets.QLabel(self.tab)
		self.label_15.setGeometry(QtCore.QRect(250, 570, 81, 21))
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		self.label_15.setFont(font)
		self.label_15.setObjectName(self._fromUtf8("label_15"))
		self.label_18 = QtWidgets.QLabel(self.tab)
		self.label_18.setGeometry(QtCore.QRect(250, 550, 81, 21))
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		self.label_18.setFont(font)
		self.label_18.setObjectName(self._fromUtf8("label_18"))
		self.graphicsView = PlotWidget(self.tab)
		self.graphicsView.setGeometry(QtCore.QRect(20, 10, 450, 400))
		self.graphicsView.setObjectName(self._fromUtf8("graphicsView"))
		self.label_7 = QtWidgets.QLabel(self.tab)
		self.label_7.setGeometry(QtCore.QRect(140, 570, 81, 21))
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		self.label_7.setFont(font)
		self.label_7.setObjectName(self._fromUtf8("label_7"))
		self.label_5 = QtWidgets.QLabel(self.tab)
		self.label_5.setGeometry(QtCore.QRect(140, 530, 81, 21))
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		self.label_5.setFont(font)
		self.label_5.setObjectName(self._fromUtf8("label_5"))
		self.label_10 = QtWidgets.QLabel(self.tab)
		self.label_10.setGeometry(QtCore.QRect(140, 600, 81, 21))
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		self.label_10.setFont(font)
		self.label_10.setObjectName(self._fromUtf8("label_10"))
		self.label_23 = QtWidgets.QLabel(self.tab)
		self.label_23.setGeometry(QtCore.QRect(250, 710, 81, 21))
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		self.label_23.setFont(font)
		self.label_23.setObjectName(self._fromUtf8("label_23"))
		self.label_9 = QtWidgets.QLabel(self.tab)
		self.label_9.setGeometry(QtCore.QRect(140, 620, 81, 21))
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		self.label_9.setFont(font)
		self.label_9.setObjectName(self._fromUtf8("label_9"))
		self.label_21 = QtWidgets.QLabel(self.tab)
		self.label_21.setGeometry(QtCore.QRect(250, 750, 81, 21))
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		self.label_21.setFont(font)
		self.label_21.setObjectName(self._fromUtf8("label_21"))
		self.label_6 = QtWidgets.QLabel(self.tab)
		self.label_6.setGeometry(QtCore.QRect(140, 550, 81, 21))
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		self.label_6.setFont(font)
		self.label_6.setObjectName(self._fromUtf8("label_6"))
		self.label_4 = QtWidgets.QLabel(self.tab)
		self.label_4.setGeometry(QtCore.QRect(110, 510, 201, 21))
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		self.label_4.setFont(font)
		self.label_4.setObjectName(self._fromUtf8("label_4"))
		self.label_13 = QtWidgets.QLabel(self.tab)
		self.label_13.setGeometry(QtCore.QRect(110, 690, 201, 21))
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		self.label_13.setFont(font)
		self.label_13.setObjectName(self._fromUtf8("label_13"))
		self.label_16 = QtWidgets.QLabel(self.tab)
		self.label_16.setGeometry(QtCore.QRect(250, 640, 81, 21))
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		self.label_16.setFont(font)
		self.label_16.setObjectName(self._fromUtf8("label_16"))
		self.label_22 = QtWidgets.QLabel(self.tab)
		self.label_22.setGeometry(QtCore.QRect(250, 730, 81, 21))
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		self.label_22.setFont(font)
		self.label_22.setObjectName(self._fromUtf8("label_22"))
		self.label_20 = QtWidgets.QLabel(self.tab)
		self.label_20.setGeometry(QtCore.QRect(250, 530, 81, 21))
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		self.label_20.setFont(font)
		self.label_20.setObjectName(self._fromUtf8("label_20"))
		self.graphicsView_2 = PlotWidget(self.tab)
		self.graphicsView_2.setGeometry(QtCore.QRect(490, 10, 771, 261))
		self.graphicsView_2.setObjectName(self._fromUtf8("graphicsView_2"))
		self.graphicsView_3 = PlotWidget(self.tab)
		self.graphicsView_3.setGeometry(QtCore.QRect(490, 570, 771, 261))
		self.graphicsView_3.setObjectName(self._fromUtf8("graphicsView_3"))
		self.label_8 = QtWidgets.QLabel(self.tab)
		self.label_8.setGeometry(QtCore.QRect(140, 640, 81, 21))
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		self.label_8.setFont(font)
		self.label_8.setObjectName(self._fromUtf8("label_8"))
		self.label_12 = QtWidgets.QLabel(self.tab)
		self.label_12.setGeometry(QtCore.QRect(140, 730, 81, 21))
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		self.label_12.setFont(font)
		self.label_12.setObjectName(self._fromUtf8("label_12"))
		self.label_19 = QtWidgets.QLabel(self.tab)
		self.label_19.setGeometry(QtCore.QRect(250, 620, 81, 21))
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		self.label_19.setFont(font)
		self.label_19.setObjectName(self._fromUtf8("label_19"))
		self.label_3.raise_()
		self.label_11.raise_()
		self.label_14.raise_()
		self.label_17.raise_()
		self.graphicsView_4.raise_()
		self.label_15.raise_()
		self.label_18.raise_()
		self.graphicsView.raise_()
		self.label_7.raise_()
		self.label_5.raise_()
		self.label_10.raise_()
		self.label_23.raise_()
		self.label_9.raise_()
		self.label_21.raise_()
		self.label_6.raise_()
		self.label_4.raise_()
		self.label_13.raise_()
		self.label_16.raise_()
		self.label_22.raise_()
		self.label_20.raise_()
		self.graphicsView_2.raise_()
		self.graphicsView_3.raise_()
		self.label_8.raise_()
		self.label_12.raise_()
		self.label_19.raise_()
		self.label_3.raise_()
		self.label_11.raise_()
		self.label_14.raise_()
		self.label_17.raise_()
		self.graphicsView_4.raise_()
		self.label_15.raise_()
		self.label_18.raise_()
		self.graphicsView.raise_()
		self.label_7.raise_()
		self.label_5.raise_()
		self.label_10.raise_()
		self.label_23.raise_()
		self.label_9.raise_()
		self.label_21.raise_()
		self.label_6.raise_()
		self.label_4.raise_()
		self.label_13.raise_()
		self.label_16.raise_()
		self.label_22.raise_()
		self.label_20.raise_()
		self.graphicsView_2.raise_()
		self.graphicsView_3.raise_()
		self.label_8.raise_()
		self.label_12.raise_()
		self.label_19.raise_()
